spring:
  application:
    name: auth-sso-service
server:
  port: 8080
#  address: 1.1.1.1
#spring:
#  application:
#    name: address-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://servicediscovery-env.bfbu3rys9v.us-east-2.elasticbeanstalk.com/eureka/
  instance:
    prefer-ip-address: true
#    ip-address: 35.198.207.177
#    instance-id: 35.198.207.177:8080
#server:
#  port: 8080
#  profiles:
#    active: default
#  cloud:
#    config:
#      enabled: true
#  eureka:
#    instance:
#      preferIpAddress: true
#    client:
#      registerWithEureka: true
#      fetchRegistry: true
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka/